version: '2'
services:
  web:
    build:
      context: ./
    restart: always
    privileged: true
    networks:
      net-app:
        ipv4_address: 10.127.2.2
    working_dir: /api/vendors
    command:
      - /api/vendors/entry-point.sh
      - ${INSTALL_SERVER}
  nginx: 
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./nginx/server.crt:/etc/nginx/server.crt:rw
      - ./nginx/server.key:/etc/nginx/server.key:rw
    restart: always
    privileged: true
    networks:
      net-app:
        ipv4_address: 10.127.2.3
  mongodb:
    image: mongo
    volumes:
      - /data/db:/data/db:rw
    restart: always
    privileged: true
    networks:
      net-app:
        ipv4_address: 10.127.2.4
networks:
  net-app:
    ipam:
      config:
        - subnet: 10.127.2.0/24

